<?php
/**
 * Registers Custom Post Types, Taxonomies, and ACF fields.
 *
 * @package Starmus\includes
 * @version 0.7.5
 * @since 0.2.0
 */

use function add_action;
use function add_filter;

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_action(
	'acf/include_fields',
	function () {
		if ( ! function_exists( 'acf_add_local_field_group' ) ) {
			return;
		}

		acf_add_local_field_group(
			array(
				'key'                   => 'group_682cba4f12a3b',
				'title'                 => 'Recording Session Metadata',
				'fields'                => array(
					array(
						'key'               => 'field_682cba6d12a3c',
						'label'             => 'Project / Collection ID',
						'name'              => 'project_collection_id',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => 'Identifier for the project or collection this session belongs to. Helps group related sessions.',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '50',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => 'e.g., Watts Riots Oral History Project',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_682cbad312a3d',
						'label'             => 'Accession Number',
						'name'              => 'accession_number',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => 'Unique accession or catalog number for this specific recording session.',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '50',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => 'e.g., 2025.06.25-A',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'                         => 'field_682cbb1a12a3e',
						'label'                       => 'Session Date',
						'name'                        => 'session_date',
						'aria-label'                  => '',
						'type'                        => 'date_picker',
						'instructions'                => 'The date the recording session took place.',
						'required'                    => 0,
						'conditional_logic'           => 0,
						'wrapper'                     => array(
							'width' => '33.33',
							'class' => '',
							'id'    => '',
						),
						'only_front'                  => 0,
						'frontend_admin_display_mode' => 'edit',
						'display_format'              => 'F j, Y',
						'return_format'               => 'Y-m-d',
						'first_day'                   => 1,
						'allow_in_bindings'           => 1,
						'default_to_current_date'     => 0,
					),
					array(
						'key'               => 'field_682cbb6d12a3f',
						'label'             => 'Session Start Time',
						'name'              => 'session_start_time',
						'aria-label'        => '',
						'type'              => 'time_picker',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '33.33',
							'class' => '',
							'id'    => '',
						),
						'display_format'    => 'g:i a',
						'return_format'     => 'H:i:s',
					),
					array(
						'key'               => 'field_682cbba712a40',
						'label'             => 'Session End Time',
						'name'              => 'session_end_time',
						'aria-label'        => '',
						'type'              => 'time_picker',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '33.33',
							'class' => '',
							'id'    => '',
						),
						'display_format'    => 'g:i a',
						'return_format'     => 'H:i:s',
					),
					array(
						'key'                         => 'field_682cbc0a12a41',
						'label'                       => 'Location',
						'name'                        => 'location',
						'aria-label'                  => '',
						'type'                        => 'text',
						'instructions'                => 'Physical place where the recording session occurred (e.g., building, room, address).',
						'required'                    => 0,
						'conditional_logic'           => 0,
						'wrapper'                     => array(
							'width' => '50',
							'class' => '',
							'id'    => '',
						),
						'only_front'                  => 0,
						'frontend_admin_display_mode' => 'edit',
						'default_value'               => '',
						'maxlength'                   => 150,
						'allow_in_bindings'           => 1,
						'placeholder'                 => 'e.g., 123 Main St, Anytown, USA',
						'prepend'                     => '',
						'append'                      => '',
					),
					array(
						'key'               => 'field_682cbc5312a42',
						'label'             => 'GPS Coordinates',
						'name'              => 'gps_coordinates',
						'aria-label'        => '',
						'type'              => 'google_map',
						'instructions'      => 'If available, the geographic coordinates of the recording location.',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '50',
							'class' => '',
							'id'    => '',
						),
						'center_lat'        => '',
						'center_lng'        => '',
						'zoom'              => '',
						'height'            => '',
					),
					array(
						'key'                         => 'field_682cbd3812a43',
						'label'                       => 'Contributor ID',
						'name'                        => 'contributor_id',
						'aria-label'                  => '',
						'type'                        => 'relationship',
						'instructions'                => 'Link to all persons who contributed oral content during this session.',
						'required'                    => 0,
						'conditional_logic'           => 0,
						'wrapper'                     => array(
							'width' => '50',
							'class' => '',
							'id'    => '',
						),
						'only_front'                  => 0,
						'frontend_admin_display_mode' => 'edit',
						'post_type'                   => '',
						'post_status'                 => '',
						'taxonomy'                    => '',
						'filters'                     => array(
							0 => 'search',
						),
						'return_format'               => 'object',
						'post_author'                 => '',
						'add_edit_post'               => 0,
						'min'                         => '',
						'max'                         => '',
						'allow_in_bindings'           => 1,
						'elements'                    => '',
						'bidirectional'               => 0,
						'bidirectional_target'        => array(),
						'post_form_template'          => '',
					),
					array(
						'key'                  => 'field_682cbdb412a44',
						'label'                => 'Interviewers / Recorders',
						'name'                 => 'interviewers_recorders',
						'aria-label'           => '',
						'type'                 => 'relationship',
						'instructions'         => 'Link to all persons who conducted the interview or operated equipment.',
						'required'             => 0,
						'conditional_logic'    => 0,
						'wrapper'              => array(
							'width' => '50',
							'class' => '',
							'id'    => '',
						),
						'post_type'            => array(
							0 => 'person',
						),
						'taxonomy'             => array(),
						'filters'              => array(
							0 => 'search',
						),
						'return_format'        => 'object',
						'multiple'             => 1,
						'min'                  => '',
						'max'                  => '',
						'ui'                   => 1,
						'allow_null'           => 0,
						'elements'             => array(),
						'bidirectional_target' => array(),
					),
					array(
						'key'                => 'field_682cbe3e12a45',
						'label'              => 'Recording Equipment',
						'name'               => 'recording_equipment',
						'aria-label'         => '',
						'type'               => 'textarea',
						'instructions'       => 'List of equipment used (e.g., microphones, recorder model, etc.) and any important settings.',
						'required'           => 0,
						'conditional_logic'  => 0,
						'wrapper'            => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'      => '',
						'new_lines'          => '',
						'rows'               => 3,
						'placeholder'        => 'Recorder: Zoom H4n
Microphone: Shure SM58',
						'maxlength'          => '',
						'acfe_textarea_code' => 0,
					),
					array(
						'key'               => 'field_682cbf3112a46',
						'label'             => 'Audio Files (Originals)',
						'name'              => 'audio_files_originals',
						'aria-label'        => '',
						'type'              => 'file',
						'instructions'      => 'Upload the original, unedited audio recordings from this session.',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '50',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
						'library'           => 'all',
						'min_size'          => '',
						'max_size'          => '',
						'mime_types'        => 'wav, aiff, flac',
						'multiple'          => 1,
						'uploader'          => '',
					),
					array(
						'key'                => 'field_682cc0b112a48',
						'label'              => 'Media Condition Notes',
						'name'               => 'media_condition_notes',
						'aria-label'         => '',
						'type'               => 'textarea',
						'instructions'       => 'Any relevant notes about the condition of the original media, background noise, or other technical issues.',
						'required'           => 0,
						'conditional_logic'  => 0,
						'wrapper'            => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'      => '',
						'new_lines'          => '',
						'rows'               => 3,
						'placeholder'        => 'e.g., Occasional background traffic noise. Hum from refrigerator in the first 10 minutes.',
						'maxlength'          => '',
						'acfe_textarea_code' => 0,
					),
					array(
						'key'                         => 'field_68cb39718100d',
						'label'                       => 'Agreement To Terms',
						'name'                        => '',
						'aria-label'                  => '',
						'type'                        => 'true_false',
						'instructions'                => '',
						'required'                    => 0,
						'conditional_logic'           => 0,
						'wrapper'                     => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'only_front'                  => 0,
						'frontend_admin_display_mode' => 'edit',
						'message'                     => '',
						'default_value'               => 0,
						'allow_in_bindings'           => 0,
						'ui'                          => 0,
						'ui_on_text'                  => '',
						'ui_off_text'                 => '',
					),
					array(
						'key'                         => 'field_68afe852920cd',
						'label'                       => 'Related Consent Agreement',
						'name'                        => 'related_consent_agreement',
						'aria-label'                  => '',
						'type'                        => 'post_object',
						'instructions'                => '',
						'required'                    => 0,
						'conditional_logic'           => 0,
						'wrapper'                     => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'only_front'                  => 0,
						'frontend_admin_display_mode' => 'edit',
						'post_type'                   => array(
							0 => 'consent-agreement',
						),
						'post_status'                 => '',
						'taxonomy'                    => '',
						'return_format'               => 'id',
						'multiple'                    => 0,
						'post_author'                 => '',
						'add_edit_post'               => 0,
						'allow_null'                  => 0,
						'allow_in_bindings'           => 0,
						'bidirectional'               => 0,
						'ui'                          => 1,
						'bidirectional_target'        => array(),
						'save_custom'                 => 0,
						'save_post_type'              => '',
						'save_post_status'            => '',
						'post_form_template'          => '',
					),
					array(
						'key'                => 'field_682cc16312a49',
						'label'              => 'Usage Restrictions / Rights',
						'name'               => 'usage_restrictions_rights',
						'aria-label'         => '',
						'type'               => 'textarea',
						'instructions'       => 'Describe any global restrictions or rights limitations that apply to all content from this session, as detailed in the consent forms.',
						'required'           => 0,
						'conditional_logic'  => 0,
						'wrapper'            => array(
							'width' => '50',
							'class' => '',
							'id'    => '',
						),
						'default_value'      => '',
						'new_lines'          => '',
						'rows'               => 4,
						'placeholder'        => 'e.g., Narrator has requested a 5-year embargo on public access, ending June 2030.',
						'maxlength'          => '',
						'acfe_textarea_code' => 0,
					),
					array(
						'key'                         => 'field_682cc20a12a4a',
						'label'                       => 'Access Level',
						'name'                        => 'access_level',
						'aria-label'                  => '',
						'type'                        => 'select',
						'instructions'                => 'Set the overall access level for the materials from this session.',
						'required'                    => 0,
						'conditional_logic'           => 0,
						'wrapper'                     => array(
							'width' => '50',
							'class' => '',
							'id'    => '',
						),
						'only_front'                  => 0,
						'frontend_admin_display_mode' => 'edit',
						'choices'                     => array(
							'public'     => 'Public',
							'restricted' => 'Restricted',
							'embargoed'  => 'Embargoed',
							'private'    => 'Private',
						),
						'default_value'               => 'public',
						'return_format'               => 'value',
						'multiple'                    => 0,
						'allow_null'                  => 0,
						'allow_in_bindings'           => 1,
						'ui'                          => 0,
						'ajax'                        => 0,
						'placeholder'                 => '',
						'create_options'              => 0,
						'save_options'                => 0,
						'allow_custom'                => 0,
						'search_placeholder'          => '',
					),
					array(
						'key'                         => 'field_68cb377b15181',
						'label'                       => 'First Pass Transcription',
						'name'                        => 'first_pass_transcription',
						'aria-label'                  => '',
						'type'                        => 'textarea',
						'instructions'                => '',
						'required'                    => 0,
						'conditional_logic'           => 0,
						'wrapper'                     => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'only_front'                  => 0,
						'frontend_admin_display_mode' => 'read_only',
						'no_values_message'           => '',
						'default_value'               => '',
						'acfe_textarea_code'          => 1,
						'maxlength'                   => '',
						'allow_in_bindings'           => 0,
						'rows'                        => '',
						'placeholder'                 => '',
						'new_lines'                   => '',
					),
					array(
						'key'                         => 'field_68cb39158100c',
						'label'                       => 'Audio Quality Score',
						'name'                        => '',
						'aria-label'                  => '',
						'type'                        => 'taxonomy',
						'instructions'                => '',
						'required'                    => 0,
						'conditional_logic'           => 0,
						'wrapper'                     => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'only_front'                  => 0,
						'frontend_admin_display_mode' => 'read_only',
						'no_values_message'           => '',
						'taxonomy'                    => 'category',
						'add_term'                    => 1,
						'save_terms'                  => 1,
						'load_terms'                  => 1,
						'return_format'               => 'id',
						'field_type'                  => 'checkbox',
						'default_value'               => '',
						'acfe_bidirectional'          => array(
							'acfe_bidirectional_enabled' => '0',
						),
						'allow_in_bindings'           => 0,
						'bidirectional'               => 0,
						'multiple'                    => 0,
						'allow_null'                  => 0,
						'bidirectional_target'        => array(),
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'audio-recording',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => 'Technical and administrative metadata for an archival recording session.',
				'show_in_rest'          => 1,
				'acfe_display_title'    => '',
				'acfe_autosync'         => '',
				'acfe_form'             => 0,
				'no_values_message'     => '',
				'acfe_meta'             => '',
				'acfe_note'             => '',
			)
		);
	}
);

add_action(
	'init',
	function () {
		register_taxonomy(
			'language',
			array(
				0 => 'audio-recording',
				1 => 'contributor',
			),
			array(
				'labels'            => array(
					'name'                       => 'Languages',
					'singular_name'              => 'Language',
					'menu_name'                  => 'Languages',
					'all_items'                  => 'All Languages',
					'edit_item'                  => 'Edit Language',
					'view_item'                  => 'View Language',
					'update_item'                => 'Update Language',
					'add_new_item'               => 'Add New Language',
					'new_item_name'              => 'New Language Name',
					'search_items'               => 'Search Languages',
					'popular_items'              => 'Popular Languages',
					'separate_items_with_commas' => 'Separate languages with commas',
					'add_or_remove_items'        => 'Add or remove languages',
					'choose_from_most_used'      => 'Choose from the most used languages',
					'not_found'                  => 'No languages found',
					'no_terms'                   => 'No languages',
					'items_list_navigation'      => 'Languages list navigation',
					'items_list'                 => 'Languages list',
					'back_to_items'              => '← Go to languages',
					'item_link'                  => 'Language Link',
					'item_link_description'      => 'A link to a language',
				),
				'description'       => 'The language spoken in an oral history.',
				'public'            => true,
				'show_in_menu'      => true,
				'show_in_rest'      => true,
				'show_admin_column' => true,
				'sort'              => true,
			)
		);

		register_taxonomy(
			'recording-type',
			array(
				0 => 'audio-recording',
			),
			array(
				'labels'            => array(
					'name'                  => 'Recording Types',
					'singular_name'         => 'Recording Type',
					'menu_name'             => 'Recording Types',
					'all_items'             => 'All Recording Types',
					'edit_item'             => 'Edit Recording Type',
					'view_item'             => 'View Recording Type',
					'update_item'           => 'Update Recording Type',
					'add_new_item'          => 'Add New Recording Type',
					'new_item_name'         => 'New Recording Type Name',
					'parent_item'           => 'Parent Recording Type',
					'parent_item_colon'     => 'Parent Recording Type:',
					'search_items'          => 'Search Recording Types',
					'not_found'             => 'No recording types found',
					'no_terms'              => 'No recording types',
					'filter_by_item'        => 'Filter by recording type',
					'items_list_navigation' => 'Recording Types list navigation',
					'items_list'            => 'Recording Types list',
					'back_to_items'         => '← Go to recording types',
					'item_link'             => 'Recording Type Link',
					'item_link_description' => 'A link to a recording type',
				),
				'description'       => 'Recording Types describe the nature and structure of the spoken material in a recorded submission.',
				'public'            => true,
				'hierarchical'      => true,
				'show_in_menu'      => true,
				'show_in_rest'      => true,
				'show_admin_column' => true,
				'rewrite'           => array(
					'hierarchical' => true,
				),
				'sort'              => true,
			)
		);
	}
);

add_action(
	'init',
	function () {
		register_post_type(
			'audio-recording',
			array(
				'labels'           => array(
					'name'                     => 'Audio Recordings',
					'singular_name'            => 'Audio Recording',
					'menu_name'                => 'Audio Recordings',
					'all_items'                => 'All Audio Recordings',
					'edit_item'                => 'Edit Audio Recording',
					'view_item'                => 'View Audio Recording',
					'view_items'               => 'View Audio Recordings',
					'add_new_item'             => 'Add Audio Recording',
					'add_new'                  => 'Add Audio Recording',
					'new_item'                 => 'New Audio Recording',
					'parent_item_colon'        => 'Parent Audio Recording:',
					'search_items'             => 'Search Audio Recordings',
					'not_found'                => 'No audio recordings found',
					'not_found_in_trash'       => 'No audio recordings found in Trash',
					'archives'                 => 'Audio Recording Archives',
					'attributes'               => 'Audio Recording Attributes',
					'insert_into_item'         => 'Insert into audio recording',
					'uploaded_to_this_item'    => 'Uploaded to this audio recording',
					'filter_items_list'        => 'Filter audio recordings list',
					'filter_by_date'           => 'Filter audio recordings by date',
					'items_list_navigation'    => 'Audio Recordings list navigation',
					'items_list'               => 'Audio Recordings list',
					'item_published'           => 'Audio Recording published.',
					'item_published_privately' => 'Audio Recording published privately.',
					'item_reverted_to_draft'   => 'Audio Recording reverted to draft.',
					'item_scheduled'           => 'Audio Recording scheduled.',
					'item_updated'             => 'Audio Recording updated.',
					'item_link'                => 'Audio Recording Link',
					'item_link_description'    => 'A link to a audio recording.',
				),
				'description'      => 'Represents a discrete field recording event with metadata like date, location, participants, and equipment used, linking multiple oral fragments and histories.',
				'public'           => true,
				'show_in_rest'     => true,
				'menu_position'    => 4,
				'menu_icon'        => 'dashicons-microphone',
				'capability_type'  => array(
					0 => 'audio recording',
					1 => 'audio recordings',
				),
				'map_meta_cap'     => true,
				'supports'         => array(
					0  => 'title',
					1  => 'author',
					2  => 'comments',
					3  => 'editor',
					4  => 'excerpt',
					5  => 'revisions',
					6  => 'page-attributes',
					7  => 'custom-fields',
					8  => 'post-formats',
					9  => 'Audio File',
					10 => 'Audio Length',
					11 => 'Annotations',
					12 => 'Latitude',
					13 => 'Longitude',
					14 => 'Agreed to Terms',
					15 => 'Author IP',
					16 => 'Author User-agent',
				),
				'taxonomies'       => array(
					0 => 'category',
					1 => 'post_tag',
					2 => 'language',
					3 => 'ambassador',
					4 => 'dialect',
					5 => 'recording-type',
				),
				'has_archive'      => 'audio-recordings',
				'delete_with_user' => false,
			)
		);
	}
);


add_filter(
	'enter_title_here',
	function ( $default, $post ) {
		switch ( $post->post_type ) {
			case 'audio-recording':
				return 'Add audio title';
		}

		return $default;
	},
	10,
	2
);
add_filter(
	'manage_audio-recording_posts_columns',
	function ( $columns ): mixed {
		$columns['recording_type'] = 'Recording Type';
		$columns['language']       = 'Language';
		$columns['ambassador']     = 'Ambassador';
		$columns['dialect']        = 'Dialect';
		$columns['date']           = 'Date';
		return $columns;
	}
);
