name: PHPStan

permissions:
  contents: read

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon'
  pull_request:
    paths:
      - '**.php'
      - 'phpstan.neon'

jobs:
  phpstan:
    name: Static Analysis (PHPStan)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, json
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Install dependencies (if needed)
        run: |
          if [ -f composer.json ]; then
            composer install --no-interaction --prefer-dist
          fi

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --configuration=phpstan.neon
